### ISSUE TITLE
INEGI Parser: Soporte a más backends de bases de datos

### ISSUE THREAD

**Issue by milmazz** [CodeandoMexico/los-scrapers#20]
Hasta ahora el script brinda soporte a MongoDB (NoSQL) y PostgreSQL (SQL), lo cual puede ser suficiente. Sin embargo, sería deseable establecer un _ORM_ como capa intermedia (_SQLAlchemy_ por ejemplo) que dependiendo de la configuración indicada por el usuario puede trabajar con conectores hacia: 
- PostgreSQL
- MySQL
- SQLite
- Oracle
- MS-SQL
- Firebird
- Sybase 

Por nombrar algunas, con _SQLAlchemy_ podríamos crear al vuelo por ejemplo las tablas de la bases de datos y controlar la inserción de datos por medio de invocaciones más orientadas a objetos y no incluir tantas sentencias SQL en el código Python.

**Comment by milmazz** [comment]
Puedo colaborar con esta labor. Quisiera conocer sus opiniones al respecto y saber si están de acuerdo.

**Comment by lalo** [comment]
Esto es interesante, ya que lo que importa es liberar los datos de la manera más sencilla y actualmente basicamente obligamos el uso MongoDB y PostgreSQL en lugar de dejar la decision al usuario final.

**Comment by milmazz** [comment]
@lalo En base a lo expuesto en el [issue 21](https://github.com/CodeandoMexico/los-scrapers/issues/21#issuecomment-39005611) quizá llegue a reconsiderar la solicitud inicial, por lo que te entendí deberíamos apuntar en ofrecer un solo _backend_ (Ej. MongoDB) y apuntar en realidad a alimentar u ofrecer un conector de datos con CKAN o en su defecto ofrecer un API para consumir fácilmente estos datos, ¿qué te parece?.

**Comment by milmazz** [comment]
Voy a cerrar este issue que lleva más de 3 años abierto, sientase libre de volverlo a abrir si aplica.
