### ISSUE TITLE
INEGI Parser: Crear scripts de distribución del paquete

### ISSUE THREAD

**Issue by milmazz** [CodeandoMexico/los-scrapers#21]
Sería deseable poder contar con los _scripts_ `setup.py`y `setup.cfg` usados en los proyectos basados en Python para distribuir las aplicaciones. Con esto finalmente sería posible publicar el proyecto en PyPI (_Python Package Index_).

**Comment by milmazz** [comment]
Puedo colaborar con esta labor. Quisiera conocer sus opiniones al respecto y saber si están de acuerdo.

**Comment by lalo** [comment]
Que tanto sentido tiene publicar los scrapers en el PyPi, ya que Codeando piensa liberar los datos producidos como un data set y las personas que quiere colaborar con el producto van a usar el código directo en Github para hacer las modificaciones. En especial (que este no es el caso) hay scrapers que hacen llamadas a servidores públicos y es muy mal visto (y mala educación) hacer llamadas innecesarias. Publicarlo como paquete en PyPi ocasionaría que la gente lo instale y lo corra para obtener los mismos resultados en lugar de descargar el dataset.

**Comment by milmazz** [comment]
De acuerdo, el objetivo principal es alimentar _datasets_ públicos o proveer mecanismos de fácil adquisición y explotación de estos datos. De todos modos ya el soporte para que cualquiera pueda instalar los _scripts_ con un simple `python setup.py install` ya se encuentra.
