### ISSUE TITLE
Seleccionar licencia para el proyecto

### ISSUE THREAD

**Issue by milmazz** [CodeandoMexico/los-scrapers#23]
En el PR #18 se propuso el uso de la licencia MIT para el proyecto `INEGIParser`, dicha propuesta fue denegada para un análisis más profundo en un hilo separado.

Para dicho análisis quisiera que se tome en cuenta lo siguiente:
- Mi comentario inicial en el [issue 18](https://github.com/CodeandoMexico/los-scrapers/pull/18#issuecomment-38977472) sobre algunos inconvenientes en el uso de la GPL.
- Mientras el proyecto _los-scrapers_ continúe sin una licencia definida se considera _por omisión_ que prefieren retener algunos derechos, lo cual podría limitar la reproducción, distribución o incluso la creación de trabajos derivados por otros. Estoy completamente seguro, que la intención de _Codeando México_ no es esta, pero hay que ser explícito en los términos de uso.
- Al estar hospedado el código en Github es claro que el autor acepto los términos de uso del sitio, lo cual habilita ciertos derechos, entre ellos la visualización del código y la creación de _forks_. Esto sin una licencia, no es suficiente.
- Otro punto en contra de los términos de la licencia GPL puede ser el encontrado en _JSON_, la licencia de _JSON_ establece una cláusula que indica lo siguiente: [The Software shall be used for Good, not Evil.](http://www.json.org/license.html), parece un tanto irracional que la FSF la catalogue de [non-free](http://www.gnu.org/licenses/license-list.html#JSON) en estos tiempos.

**Comment by lalo** [comment]
La discusion interna del equipo fue escoger la licencia AGPL-3.0. Recomendada por los nuevos guidelines de Codeando México https://github.com/CodeandoMexico/repo-guidelines

Es importante mencionar que se pueden usar los scrapers para usos comerciales y en ese caso es importante que liberen el código y los cambios que se realizaron.
