### ISSUE TITLE
Actualizar README

### ISSUE THREAD

**Issue by juanpabloe** [CodeandoMexico/los-scrapers#24]
Los Scrapers es una recopilación de web scrapers para hacer accesibles datos públicos de México. 

A partir de Abril 2014 cambiaremos la estructura del proyecto por propuesta de @lalo:
- Cada scraper estará en un repositorio independiente, con su propio README.
- Este repo "los-scrapers" será un index de los demás scrapers, con breves guidelines para compartir un scraper, la licencia, como crear uno (newbie-friendliness) y como publicar los datos abiertos (posiblemente usando datamx.io).
- El issue tracker de "los-scrapers" será para compartir nuevas ideas de scrapers o compartir uno que ya está funcionando al index.

Nuevas ideas para agregar al README como siempre bienvenidas!

![A-team](http://badmouth.net/wp-content/uploads/2003/11/a-team.jpg)

**Comment by lalo** [comment]
También se podría agregar un apartado para otros scrapers que no forman parte de Codeando México pero son relevantes y publicados por otras personas

**Comment by juanpabloe** [comment]
Suena bien, en ese caso solamente tendrían que lanzar un PR a este repo que agregue al index su scraper, á-la [github government](https://government.github.com/community/)

**Comment by defvol** [comment]
Deberíamos meter al loop a @mekler

Tiene un buen de scrapers https://gist.github.com/mekler

**Comment by lalo** [comment]
@rodowi interesante, si el chiste sera compilar diversos scrapers o adoptarlos si su impacto es alto y estan abandonados

**Comment by mekler** [comment]
@lalo @rodowi me gusta la idea. hace falta. cómo le entro?

**Comment by lalo** [comment]
@mekler ya se actualizo el readme, el chiste es si tu tienes un buen scraper solo agrégalo a la lista como un link como el que ya viene y en un pull request se agrega a nuestra lista. después estamos en contacto dependiendo si tienes una idea interesante o alguna propuesta a travez de issues y si quieres dale watch al repo si estas muy interesado. saludos y que buena onda que andas en lo mismo de scraping! gracias

**Comment by juanpabloe** [comment]
@lalo el buen @mekler es un viejo conocido del equipo

@mekler lánzanos un PR con tus scrapers. si los puedes pasar de gists a un repositorio con su readme sencillo cada uno estaría muy bueno!

**Comment by mekler** [comment]
va. le voy a decicar un par de días la siguiente semana para que pueda compartirlo.
